// Code generated by go generate; DO NOT EDIT.
package task

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/task/types"
	"github.com/yunify/qsctl/v2/task/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// CopyTask will the root copy task.
type CopyTask struct {
	// Inherited value

	// Runtime value
	types.Todo
	types.BucketName
	types.FlowType
	types.Key
	types.KeyType
	types.Path
	types.PathType
	types.Pool
	types.Storage
	types.Stream
}

// Run implement navvy.Task
func (t *CopyTask) Run() {
	utils.SubmitNextTask(t)
}

// Wait will wait until CopyTask has been finished
func (t *CopyTask) Wait() {
	t.GetPool().Wait()
}
