// Code generated by go generate; DO NOT EDIT.
package task

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/task/types"
	"github.com/yunify/qsctl/v2/task/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// CopyPartialStreamTask will .
type CopyPartialStreamTask struct {
	// Inherited value
	types.Pool
	types.Size
	types.Path
	types.ObjectKey
	types.Storage
	types.UploadID
	types.PartNumber
	types.Offset
	types.WaitGroup

	// Runtime value
	types.Todo
	types.MD5Sum
	types.Content
}

// Run implement navvy.Task
func (t *CopyPartialStreamTask) Run() {
	utils.SubmitNextTask(t)
}
