// Code generated by go generate; DO NOT EDIT.
package task

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/task/types"
	"github.com/yunify/qsctl/v2/task/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// CopyPartialStreamTask will copy a partial stream to storage.
type CopyPartialStreamTask struct {
	// Inherited value
	types.Pool
	types.Key
	types.Storage
	types.UploadID
	types.WaitGroup

	// Runtime value
	types.Todo
	types.MD5Sum
	types.Content
	types.Size
	types.PartNumber
}

// Run implement navvy.Task
func (t *CopyPartialStreamTask) Run() {
	utils.SubmitNextTask(t)
}

// initCopyPartialStreamTask will create a CopyPartialStreamTask and fetch inherited data from CopyStreamTask.
func initCopyPartialStreamTask(task types.Todoist) (t *CopyPartialStreamTask, o *CopyStreamTask) {
	o, ok := task.(*CopyStreamTask)
	if !ok {
		panic("parent task is not a CopyStreamTask")
	}

	t = &CopyPartialStreamTask{}
	t.SetPool(o.GetPool())
	t.SetKey(o.GetKey())
	t.SetStorage(o.GetStorage())
	t.SetUploadID(o.GetUploadID())
	t.SetWaitGroup(o.GetWaitGroup())
	return
}

// CopyStreamTask will copy a stream to storage.
type CopyStreamTask struct {
	// Inherited value
	types.Pool
	types.Storage
	types.Path
	types.Key

	// Runtime value
	types.Todo
	types.Size
	types.Stream
	types.TaskConstructor
	types.CurrentPartNumber
	types.CurrentOffset
	types.BytesPool
	types.PartSize
	types.UploadID
	types.WaitGroup
}

// Run implement navvy.Task
func (t *CopyStreamTask) Run() {
	utils.SubmitNextTask(t)
}

// initCopyStreamTask will create a CopyStreamTask and fetch inherited data from CopyTask.
func initCopyStreamTask(task types.Todoist) (t *CopyStreamTask, o *CopyTask) {
	o, ok := task.(*CopyTask)
	if !ok {
		panic("parent task is not a CopyTask")
	}

	t = &CopyStreamTask{}
	t.SetPool(o.GetPool())
	t.SetStorage(o.GetStorage())
	t.SetPath(o.GetPath())
	t.SetKey(o.GetKey())
	return
}
