// Code generated by go generate; DO NOT EDIT.
package task

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/pkg/types"
	"github.com/yunify/qsctl/v2/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// copyTaskRequirement is the requirement for execute CopyTask.
type copyTaskRequirement interface {
	navvy.Task

	// Inherited value
}

// mockCopyTask is the mock task for CopyTask.
type mockCopyTask struct {
	types.Todo
	types.Pool

	// Inherited value
}

func (t *mockCopyTask) Run() {
	panic("mockCopyTask should not be run.")
}

// CopyTask will the root copy task.
type CopyTask struct {
	copyTaskRequirement

	// Runtime value
	types.Todo
	types.BucketName
	types.FlowType
	types.Key
	types.KeyType
	types.Path
	types.PathType
	types.Pool
	types.Storage
	types.Stream
}

// Run implement navvy.Task
func (t *CopyTask) Run() {
	utils.SubmitNextTask(t)
}

// Wait will wait until CopyTask has been finished
func (t *CopyTask) Wait() {
	t.GetPool().Wait()
}
