// Code generated by go generate; DO NOT EDIT.
package task

import (
	"fmt"

	"github.com/Xuanwo/navvy"
	"github.com/google/uuid"

	"github.com/yunify/qsctl/v2/pkg/schedule"
	"github.com/yunify/qsctl/v2/pkg/types"
)

var _ navvy.Pool
var _ types.Pool
var _ = uuid.New()

// copyFileTaskRequirement is the requirement for execute CopyFileTask.
type copyFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
}

// mockCopyFileTask is the mock task for CopyFileTask.
type mockCopyFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.DestinationPath
	types.DestinationStorage
	types.SourcePath
	types.SourceStorage
}

func (t *mockCopyFileTask) Run() {
	panic("mockCopyFileTask should not be run.")
}

// CopyFileTask will copy a file between two storager.
type CopyFileTask struct {
	copyFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.TotalSize
}

// Run implement navvy.Task
func (t *CopyFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *CopyFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task CopyFile failed: {%w}", err))
}

// NewCopyFile will create a CopyFileTask struct and fetch inherited data from parent task.
func NewCopyFile(task navvy.Task) *CopyFileTask {
	t := &CopyFileTask{
		copyFileTaskRequirement: task.(copyFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewCopyFileTask will create a CopyFileTask and fetch inherited data from parent task.
func NewCopyFileTask(task navvy.Task) navvy.Task {
	return NewCopyFile(task)
}

// copyFileShimTaskRequirement is the requirement for execute CopyFileShimTask.
type copyFileShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter

	// Mutable value
	types.TotalSizeSetter
}

// copyFileShimTask will Storage shim task for .
type copyFileShimTask struct {
	copyFileShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *copyFileShimTask) Run() {}

// newCopyFileShim will create a copyFileShimTask struct and fetch inherited data from parent task.
func newCopyFileShim(task navvy.Task) *copyFileShimTask {
	t := &copyFileShimTask{
		copyFileShimTaskRequirement: task.(copyFileShimTaskRequirement),
	}
	return t
}

// copyLargeFileTaskRequirement is the requirement for execute CopyLargeFileTask.
type copyLargeFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter

	// Mutable value
}

// mockCopyLargeFileTask is the mock task for CopyLargeFileTask.
type mockCopyLargeFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.DestinationPath
	types.DestinationStorage
	types.SourcePath
	types.SourceStorage
	types.TotalSize
}

func (t *mockCopyLargeFileTask) Run() {
	panic("mockCopyLargeFileTask should not be run.")
}

// CopyLargeFileTask will copy a large file between two storager.
type CopyLargeFileTask struct {
	copyLargeFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.PartSize
	types.ScheduleFunc
	types.SegmentID
}

// Run implement navvy.Task
func (t *CopyLargeFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *CopyLargeFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task CopyLargeFile failed: {%w}", err))
}

// NewCopyLargeFile will create a CopyLargeFileTask struct and fetch inherited data from parent task.
func NewCopyLargeFile(task navvy.Task) *CopyLargeFileTask {
	t := &CopyLargeFileTask{
		copyLargeFileTaskRequirement: task.(copyLargeFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewCopyLargeFileTask will create a CopyLargeFileTask and fetch inherited data from parent task.
func NewCopyLargeFileTask(task navvy.Task) navvy.Task {
	return NewCopyLargeFile(task)
}

// copyLargeFileShimTaskRequirement is the requirement for execute CopyLargeFileShimTask.
type copyLargeFileShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter
	types.PartSizeGetter
	types.ScheduleFuncGetter
	types.SegmentIDGetter

	// Mutable value
	types.PartSizeSetter
	types.ScheduleFuncSetter
	types.SegmentIDSetter
}

// copyLargeFileShimTask will Storage shim task for .
type copyLargeFileShimTask struct {
	copyLargeFileShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *copyLargeFileShimTask) Run() {}

// newCopyLargeFileShim will create a copyLargeFileShimTask struct and fetch inherited data from parent task.
func newCopyLargeFileShim(task navvy.Task) *copyLargeFileShimTask {
	t := &copyLargeFileShimTask{
		copyLargeFileShimTaskRequirement: task.(copyLargeFileShimTaskRequirement),
	}
	return t
}

// copyPartialFileTaskRequirement is the requirement for execute CopyPartialFileTask.
type copyPartialFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.OffsetGetter
	types.PartSizeGetter
	types.SegmentIDGetter
	types.SizeGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter

	// Mutable value
	types.SizeSetter
	types.DoneSetter
}

// mockCopyPartialFileTask is the mock task for CopyPartialFileTask.
type mockCopyPartialFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.DestinationStorage
	types.Offset
	types.Size
	types.SourcePath
	types.Done
	types.DestinationPath
	types.PartSize
	types.SegmentID
	types.SourceStorage
	types.TotalSize
}

func (t *mockCopyPartialFileTask) Run() {
	panic("mockCopyPartialFileTask should not be run.")
}

// CopyPartialFileTask will copy a partial file to between two storager.
type CopyPartialFileTask struct {
	copyPartialFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.MD5Sum
}

// Run implement navvy.Task
func (t *CopyPartialFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *CopyPartialFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task CopyPartialFile failed: {%w}", err))
}

// NewCopyPartialFile will create a CopyPartialFileTask struct and fetch inherited data from parent task.
func NewCopyPartialFile(task navvy.Task) *CopyPartialFileTask {
	t := &CopyPartialFileTask{
		copyPartialFileTaskRequirement: task.(copyPartialFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewCopyPartialFileTask will create a CopyPartialFileTask and fetch inherited data from parent task.
func NewCopyPartialFileTask(task navvy.Task) navvy.Task {
	return NewCopyPartialFile(task)
}

// copyPartialFileShimTaskRequirement is the requirement for execute CopyPartialFileShimTask.
type copyPartialFileShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.OffsetGetter
	types.PartSizeGetter
	types.SegmentIDGetter
	types.SizeGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter
	types.MD5SumGetter

	// Mutable value
	types.SizeSetter
	types.DoneSetter
	types.MD5SumSetter
}

// copyPartialFileShimTask will Storage shim task for .
type copyPartialFileShimTask struct {
	copyPartialFileShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *copyPartialFileShimTask) Run() {}

// newCopyPartialFileShim will create a copyPartialFileShimTask struct and fetch inherited data from parent task.
func newCopyPartialFileShim(task navvy.Task) *copyPartialFileShimTask {
	t := &copyPartialFileShimTask{
		copyPartialFileShimTaskRequirement: task.(copyPartialFileShimTaskRequirement),
	}
	return t
}

// copyPartialStreamTaskRequirement is the requirement for execute CopyPartialStreamTask.
type copyPartialStreamTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.BytesPoolGetter
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.PartSizeGetter
	types.SegmentIDGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
	types.SizeSetter
	types.DoneSetter
}

// mockCopyPartialStreamTask is the mock task for CopyPartialStreamTask.
type mockCopyPartialStreamTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.BytesPool
	types.DestinationPath
	types.SegmentID
	types.Size
	types.Done
	types.DestinationStorage
	types.PartSize
	types.SourcePath
	types.SourceStorage
}

func (t *mockCopyPartialStreamTask) Run() {
	panic("mockCopyPartialStreamTask should not be run.")
}

// CopyPartialStreamTask will copy a partial stream between two storager.
type CopyPartialStreamTask struct {
	copyPartialStreamTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.Content
	types.MD5Sum
}

// Run implement navvy.Task
func (t *CopyPartialStreamTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *CopyPartialStreamTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task CopyPartialStream failed: {%w}", err))
}

// NewCopyPartialStream will create a CopyPartialStreamTask struct and fetch inherited data from parent task.
func NewCopyPartialStream(task navvy.Task) *CopyPartialStreamTask {
	t := &CopyPartialStreamTask{
		copyPartialStreamTaskRequirement: task.(copyPartialStreamTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewCopyPartialStreamTask will create a CopyPartialStreamTask and fetch inherited data from parent task.
func NewCopyPartialStreamTask(task navvy.Task) navvy.Task {
	return NewCopyPartialStream(task)
}

// copyPartialStreamShimTaskRequirement is the requirement for execute CopyPartialStreamShimTask.
type copyPartialStreamShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.BytesPoolGetter
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.PartSizeGetter
	types.SegmentIDGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.ContentGetter
	types.MD5SumGetter

	// Mutable value
	types.SizeSetter
	types.DoneSetter
	types.ContentSetter
	types.MD5SumSetter
}

// copyPartialStreamShimTask will Storage shim task for .
type copyPartialStreamShimTask struct {
	copyPartialStreamShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *copyPartialStreamShimTask) Run() {}

// newCopyPartialStreamShim will create a copyPartialStreamShimTask struct and fetch inherited data from parent task.
func newCopyPartialStreamShim(task navvy.Task) *copyPartialStreamShimTask {
	t := &copyPartialStreamShimTask{
		copyPartialStreamShimTaskRequirement: task.(copyPartialStreamShimTaskRequirement),
	}
	return t
}

// copySmallFileTaskRequirement is the requirement for execute CopySmallFileTask.
type copySmallFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter

	// Mutable value
}

// mockCopySmallFileTask is the mock task for CopySmallFileTask.
type mockCopySmallFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.TotalSize
	types.DestinationPath
	types.DestinationStorage
	types.SourcePath
	types.SourceStorage
}

func (t *mockCopySmallFileTask) Run() {
	panic("mockCopySmallFileTask should not be run.")
}

// CopySmallFileTask will copy a small file between two storager.
type CopySmallFileTask struct {
	copySmallFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.MD5Sum
	types.Offset
	types.Size
}

// Run implement navvy.Task
func (t *CopySmallFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *CopySmallFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task CopySmallFile failed: {%w}", err))
}

// NewCopySmallFile will create a CopySmallFileTask struct and fetch inherited data from parent task.
func NewCopySmallFile(task navvy.Task) *CopySmallFileTask {
	t := &CopySmallFileTask{
		copySmallFileTaskRequirement: task.(copySmallFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewCopySmallFileTask will create a CopySmallFileTask and fetch inherited data from parent task.
func NewCopySmallFileTask(task navvy.Task) navvy.Task {
	return NewCopySmallFile(task)
}

// copySmallFileShimTaskRequirement is the requirement for execute CopySmallFileShimTask.
type copySmallFileShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter
	types.MD5SumGetter
	types.OffsetGetter
	types.SizeGetter

	// Mutable value
	types.MD5SumSetter
	types.OffsetSetter
	types.SizeSetter
}

// copySmallFileShimTask will Storage shim task for .
type copySmallFileShimTask struct {
	copySmallFileShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *copySmallFileShimTask) Run() {}

// newCopySmallFileShim will create a copySmallFileShimTask struct and fetch inherited data from parent task.
func newCopySmallFileShim(task navvy.Task) *copySmallFileShimTask {
	t := &copySmallFileShimTask{
		copySmallFileShimTaskRequirement: task.(copySmallFileShimTaskRequirement),
	}
	return t
}

// copyStreamTaskRequirement is the requirement for execute CopyStreamTask.
type copyStreamTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
}

// mockCopyStreamTask is the mock task for CopyStreamTask.
type mockCopyStreamTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.DestinationPath
	types.DestinationStorage
	types.SourcePath
	types.SourceStorage
}

func (t *mockCopyStreamTask) Run() {
	panic("mockCopyStreamTask should not be run.")
}

// CopyStreamTask will copy a stream between two storager.
type CopyStreamTask struct {
	copyStreamTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.BytesPool
	types.CurrentOffset
	types.PartSize
	types.ScheduleFunc
	types.SegmentID
	types.TotalSize
}

// Run implement navvy.Task
func (t *CopyStreamTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *CopyStreamTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task CopyStream failed: {%w}", err))
}

// NewCopyStream will create a CopyStreamTask struct and fetch inherited data from parent task.
func NewCopyStream(task navvy.Task) *CopyStreamTask {
	t := &CopyStreamTask{
		copyStreamTaskRequirement: task.(copyStreamTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewCopyStreamTask will create a CopyStreamTask and fetch inherited data from parent task.
func NewCopyStreamTask(task navvy.Task) navvy.Task {
	return NewCopyStream(task)
}

// copyStreamShimTaskRequirement is the requirement for execute CopyStreamShimTask.
type copyStreamShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.BytesPoolGetter
	types.CurrentOffsetGetter
	types.PartSizeGetter
	types.ScheduleFuncGetter
	types.SegmentIDGetter
	types.TotalSizeGetter

	// Mutable value
	types.BytesPoolSetter
	types.CurrentOffsetSetter
	types.PartSizeSetter
	types.ScheduleFuncSetter
	types.SegmentIDSetter
	types.TotalSizeSetter
}

// copyStreamShimTask will Storage shim task for .
type copyStreamShimTask struct {
	copyStreamShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *copyStreamShimTask) Run() {}

// newCopyStreamShim will create a copyStreamShimTask struct and fetch inherited data from parent task.
func newCopyStreamShim(task navvy.Task) *copyStreamShimTask {
	t := &copyStreamShimTask{
		copyStreamShimTaskRequirement: task.(copyStreamShimTaskRequirement),
	}
	return t
}

// createStorageTaskRequirement is the requirement for execute CreateStorageTask.
type createStorageTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ServiceGetter
	types.StorageNameGetter
	types.ZoneGetter

	// Mutable value
}

// mockCreateStorageTask is the mock task for CreateStorageTask.
type mockCreateStorageTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Service
	types.StorageName
	types.Zone
}

func (t *mockCreateStorageTask) Run() {
	panic("mockCreateStorageTask should not be run.")
}

// CreateStorageTask will create a storage.
type CreateStorageTask struct {
	createStorageTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *CreateStorageTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *CreateStorageTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task CreateStorage failed: {%w}", err))
}

// NewCreateStorage will create a CreateStorageTask struct and fetch inherited data from parent task.
func NewCreateStorage(task navvy.Task) *CreateStorageTask {
	t := &CreateStorageTask{
		createStorageTaskRequirement: task.(createStorageTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewCreateStorageTask will create a CreateStorageTask and fetch inherited data from parent task.
func NewCreateStorageTask(task navvy.Task) navvy.Task {
	return NewCreateStorage(task)
}

// deleteDirTaskRequirement is the requirement for execute DeleteDirTask.
type deleteDirTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.PathGetter
	types.StorageGetter

	// Mutable value
}

// mockDeleteDirTask is the mock task for DeleteDirTask.
type mockDeleteDirTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Storage
	types.Path
}

func (t *mockDeleteDirTask) Run() {
	panic("mockDeleteDirTask should not be run.")
}

// DeleteDirTask will will delete a dir recursively.
type DeleteDirTask struct {
	deleteDirTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.ObjectChannel
	types.Recursive
	types.ScheduleFunc
}

// Run implement navvy.Task
func (t *DeleteDirTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *DeleteDirTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task DeleteDir failed: {%w}", err))
}

// NewDeleteDir will create a DeleteDirTask struct and fetch inherited data from parent task.
func NewDeleteDir(task navvy.Task) *DeleteDirTask {
	t := &DeleteDirTask{
		deleteDirTaskRequirement: task.(deleteDirTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewDeleteDirTask will create a DeleteDirTask and fetch inherited data from parent task.
func NewDeleteDirTask(task navvy.Task) navvy.Task {
	return NewDeleteDir(task)
}

// deleteFileTaskRequirement is the requirement for execute DeleteFileTask.
type deleteFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.PathGetter
	types.StorageGetter

	// Mutable value
}

// mockDeleteFileTask is the mock task for DeleteFileTask.
type mockDeleteFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Path
	types.Storage
}

func (t *mockDeleteFileTask) Run() {
	panic("mockDeleteFileTask should not be run.")
}

// DeleteFileTask will will delete a file from storage.
type DeleteFileTask struct {
	deleteFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *DeleteFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *DeleteFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task DeleteFile failed: {%w}", err))
}

// NewDeleteFile will create a DeleteFileTask struct and fetch inherited data from parent task.
func NewDeleteFile(task navvy.Task) *DeleteFileTask {
	t := &DeleteFileTask{
		deleteFileTaskRequirement: task.(deleteFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewDeleteFileTask will create a DeleteFileTask and fetch inherited data from parent task.
func NewDeleteFileTask(task navvy.Task) navvy.Task {
	return NewDeleteFile(task)
}

// deleteStorageTaskRequirement is the requirement for execute DeleteStorageTask.
type deleteStorageTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ServiceGetter
	types.StorageNameGetter

	// Mutable value
}

// mockDeleteStorageTask is the mock task for DeleteStorageTask.
type mockDeleteStorageTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Service
	types.StorageName
}

func (t *mockDeleteStorageTask) Run() {
	panic("mockDeleteStorageTask should not be run.")
}

// DeleteStorageTask will delete a storage.
type DeleteStorageTask struct {
	deleteStorageTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *DeleteStorageTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *DeleteStorageTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task DeleteStorage failed: {%w}", err))
}

// NewDeleteStorage will create a DeleteStorageTask struct and fetch inherited data from parent task.
func NewDeleteStorage(task navvy.Task) *DeleteStorageTask {
	t := &DeleteStorageTask{
		deleteStorageTaskRequirement: task.(deleteStorageTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewDeleteStorageTask will create a DeleteStorageTask and fetch inherited data from parent task.
func NewDeleteStorageTask(task navvy.Task) navvy.Task {
	return NewDeleteStorage(task)
}

// deleteStorageForceTaskRequirement is the requirement for execute DeleteStorageForceTask.
type deleteStorageForceTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ServiceGetter
	types.StorageNameGetter

	// Mutable value
}

// mockDeleteStorageForceTask is the mock task for DeleteStorageForceTask.
type mockDeleteStorageForceTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Service
	types.StorageName
}

func (t *mockDeleteStorageForceTask) Run() {
	panic("mockDeleteStorageForceTask should not be run.")
}

// DeleteStorageForceTask will remove a bucket force.
type DeleteStorageForceTask struct {
	deleteStorageForceTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.ObjectChannel
}

// Run implement navvy.Task
func (t *DeleteStorageForceTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *DeleteStorageForceTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task DeleteStorageForce failed: {%w}", err))
}

// NewDeleteStorageForce will create a DeleteStorageForceTask struct and fetch inherited data from parent task.
func NewDeleteStorageForce(task navvy.Task) *DeleteStorageForceTask {
	t := &DeleteStorageForceTask{
		deleteStorageForceTaskRequirement: task.(deleteStorageForceTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewDeleteStorageForceTask will create a DeleteStorageForceTask and fetch inherited data from parent task.
func NewDeleteStorageForceTask(task navvy.Task) navvy.Task {
	return NewDeleteStorageForce(task)
}

// fileCopyTaskRequirement is the requirement for execute FileCopyTask.
type fileCopyTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.MD5SumGetter
	types.SizeGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
}

// mockFileCopyTask is the mock task for FileCopyTask.
type mockFileCopyTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.SourcePath
	types.SourceStorage
	types.DestinationPath
	types.DestinationStorage
	types.MD5Sum
	types.Size
}

func (t *mockFileCopyTask) Run() {
	panic("mockFileCopyTask should not be run.")
}

// FileCopyTask will execute a file copy operation between towo storager.
type FileCopyTask struct {
	fileCopyTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *FileCopyTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *FileCopyTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task FileCopy failed: {%w}", err))
}

// NewFileCopy will create a FileCopyTask struct and fetch inherited data from parent task.
func NewFileCopy(task navvy.Task) *FileCopyTask {
	t := &FileCopyTask{
		fileCopyTaskRequirement: task.(fileCopyTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewFileCopyTask will create a FileCopyTask and fetch inherited data from parent task.
func NewFileCopyTask(task navvy.Task) navvy.Task {
	return NewFileCopy(task)
}

// fileCopyShimTaskRequirement is the requirement for execute FileCopyShimTask.
type fileCopyShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.MD5SumGetter
	types.SizeGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
}

// fileCopyShimTask will Storage shim task for .
type fileCopyShimTask struct {
	fileCopyShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *fileCopyShimTask) Run() {}

// newFileCopyShim will create a fileCopyShimTask struct and fetch inherited data from parent task.
func newFileCopyShim(task navvy.Task) *fileCopyShimTask {
	t := &fileCopyShimTask{
		fileCopyShimTaskRequirement: task.(fileCopyShimTaskRequirement),
	}
	return t
}

// fileMD5SumTaskRequirement is the requirement for execute FileMD5SumTask.
type fileMD5SumTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.OffsetGetter
	types.SizeGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
	types.MD5SumSetter
}

// mockFileMD5SumTask is the mock task for FileMD5SumTask.
type mockFileMD5SumTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Offset
	types.Size
	types.SourcePath
	types.SourceStorage
	types.MD5Sum
}

func (t *mockFileMD5SumTask) Run() {
	panic("mockFileMD5SumTask should not be run.")
}

// FileMD5SumTask will get file's md5 sum.
type FileMD5SumTask struct {
	fileMD5SumTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *FileMD5SumTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *FileMD5SumTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task FileMD5Sum failed: {%w}", err))
}

// NewFileMD5Sum will create a FileMD5SumTask struct and fetch inherited data from parent task.
func NewFileMD5Sum(task navvy.Task) *FileMD5SumTask {
	t := &FileMD5SumTask{
		fileMD5SumTaskRequirement: task.(fileMD5SumTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewFileMD5SumTask will create a FileMD5SumTask and fetch inherited data from parent task.
func NewFileMD5SumTask(task navvy.Task) navvy.Task {
	return NewFileMD5Sum(task)
}

// fileShimTaskRequirement is the requirement for execute FileShimTask.
type fileShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.StorageGetter

	// Mutable value
}

// fileShimTask will a shim for file operation.
type fileShimTask struct {
	fileShimTaskRequirement

	// Runtime value
	types.Path
}

// Run implement navvy.Task
func (t *fileShimTask) Run() {}

// newFileShim will create a fileShimTask struct and fetch inherited data from parent task.
func newFileShim(task navvy.Task) *fileShimTask {
	t := &fileShimTask{
		fileShimTaskRequirement: task.(fileShimTaskRequirement),
	}
	return t
}

// iterateFileTaskRequirement is the requirement for execute IterateFileTask.
type iterateFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.PathGetter
	types.RecursiveGetter
	types.ScheduleFuncGetter
	types.StorageGetter

	// Mutable value
}

// mockIterateFileTask is the mock task for IterateFileTask.
type mockIterateFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Path
	types.Recursive
	types.ScheduleFunc
	types.Storage
}

func (t *mockIterateFileTask) Run() {
	panic("mockIterateFileTask should not be run.")
}

// IterateFileTask will iterate file and execute operations on it.
type IterateFileTask struct {
	iterateFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.ObjectChannel
	types.Path
}

// Run implement navvy.Task
func (t *IterateFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *IterateFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task IterateFile failed: {%w}", err))
}

// NewIterateFile will create a IterateFileTask struct and fetch inherited data from parent task.
func NewIterateFile(task navvy.Task) *IterateFileTask {
	t := &IterateFileTask{
		iterateFileTaskRequirement: task.(iterateFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewIterateFileTask will create a IterateFileTask and fetch inherited data from parent task.
func NewIterateFileTask(task navvy.Task) navvy.Task {
	return NewIterateFile(task)
}

// listFileTaskRequirement is the requirement for execute ListFileTask.
type listFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ObjectChannelGetter
	types.PathGetter
	types.RecursiveGetter
	types.StorageGetter

	// Mutable value
}

// mockListFileTask is the mock task for ListFileTask.
type mockListFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.ObjectChannel
	types.Path
	types.Recursive
	types.Storage
}

func (t *mockListFileTask) Run() {
	panic("mockListFileTask should not be run.")
}

// ListFileTask will list files.
type ListFileTask struct {
	listFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *ListFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *ListFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task ListFile failed: {%w}", err))
}

// NewListFile will create a ListFileTask struct and fetch inherited data from parent task.
func NewListFile(task navvy.Task) *ListFileTask {
	t := &ListFileTask{
		listFileTaskRequirement: task.(listFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewListFileTask will create a ListFileTask and fetch inherited data from parent task.
func NewListFileTask(task navvy.Task) navvy.Task {
	return NewListFile(task)
}

// listStorageTaskRequirement is the requirement for execute ListStorageTask.
type listStorageTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ServiceGetter
	types.ZoneGetter

	// Mutable value
}

// mockListStorageTask is the mock task for ListStorageTask.
type mockListStorageTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Service
	types.Zone
}

func (t *mockListStorageTask) Run() {
	panic("mockListStorageTask should not be run.")
}

// ListStorageTask will send get request to get bucket list.
type ListStorageTask struct {
	listStorageTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.BucketList
}

// Run implement navvy.Task
func (t *ListStorageTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *ListStorageTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task ListStorage failed: {%w}", err))
}

// NewListStorage will create a ListStorageTask struct and fetch inherited data from parent task.
func NewListStorage(task navvy.Task) *ListStorageTask {
	t := &ListStorageTask{
		listStorageTaskRequirement: task.(listStorageTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewListStorageTask will create a ListStorageTask and fetch inherited data from parent task.
func NewListStorageTask(task navvy.Task) navvy.Task {
	return NewListStorage(task)
}

// reachFileTaskRequirement is the requirement for execute ReachFileTask.
type reachFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ExpireGetter
	types.PathGetter
	types.StorageGetter

	// Mutable value
}

// mockReachFileTask is the mock task for ReachFileTask.
type mockReachFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Expire
	types.Path
	types.Storage
}

func (t *mockReachFileTask) Run() {
	panic("mockReachFileTask should not be run.")
}

// ReachFileTask will will reach a remote object and return the signed url.
type ReachFileTask struct {
	reachFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.URL
}

// Run implement navvy.Task
func (t *ReachFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *ReachFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task ReachFile failed: {%w}", err))
}

// NewReachFile will create a ReachFileTask struct and fetch inherited data from parent task.
func NewReachFile(task navvy.Task) *ReachFileTask {
	t := &ReachFileTask{
		reachFileTaskRequirement: task.(reachFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewReachFileTask will create a ReachFileTask and fetch inherited data from parent task.
func NewReachFileTask(task navvy.Task) navvy.Task {
	return NewReachFile(task)
}

// segmentAbortAllTaskRequirement is the requirement for execute SegmentAbortAllTask.
type segmentAbortAllTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.StorageGetter
	types.StorageNameGetter

	// Mutable value
}

// mockSegmentAbortAllTask is the mock task for SegmentAbortAllTask.
type mockSegmentAbortAllTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Storage
	types.StorageName
}

func (t *mockSegmentAbortAllTask) Run() {
	panic("mockSegmentAbortAllTask should not be run.")
}

// SegmentAbortAllTask will abort all multipart uploads in a bucket.
type SegmentAbortAllTask struct {
	segmentAbortAllTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *SegmentAbortAllTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *SegmentAbortAllTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task SegmentAbortAll failed: {%w}", err))
}

// NewSegmentAbortAll will create a SegmentAbortAllTask struct and fetch inherited data from parent task.
func NewSegmentAbortAll(task navvy.Task) *SegmentAbortAllTask {
	t := &SegmentAbortAllTask{
		segmentAbortAllTaskRequirement: task.(segmentAbortAllTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewSegmentAbortAllTask will create a SegmentAbortAllTask and fetch inherited data from parent task.
func NewSegmentAbortAllTask(task navvy.Task) navvy.Task {
	return NewSegmentAbortAll(task)
}

// segmentCompleteTaskRequirement is the requirement for execute SegmentCompleteTask.
type segmentCompleteTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.PathGetter
	types.SegmentIDGetter
	types.StorageGetter

	// Mutable value
}

// mockSegmentCompleteTask is the mock task for SegmentCompleteTask.
type mockSegmentCompleteTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Storage
	types.Path
	types.SegmentID
}

func (t *mockSegmentCompleteTask) Run() {
	panic("mockSegmentCompleteTask should not be run.")
}

// SegmentCompleteTask will complete a segment.
type SegmentCompleteTask struct {
	segmentCompleteTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *SegmentCompleteTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *SegmentCompleteTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task SegmentComplete failed: {%w}", err))
}

// NewSegmentComplete will create a SegmentCompleteTask struct and fetch inherited data from parent task.
func NewSegmentComplete(task navvy.Task) *SegmentCompleteTask {
	t := &SegmentCompleteTask{
		segmentCompleteTaskRequirement: task.(segmentCompleteTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewSegmentCompleteTask will create a SegmentCompleteTask and fetch inherited data from parent task.
func NewSegmentCompleteTask(task navvy.Task) navvy.Task {
	return NewSegmentComplete(task)
}

// segmentFileCopyTaskRequirement is the requirement for execute SegmentFileCopyTask.
type segmentFileCopyTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.MD5SumGetter
	types.OffsetGetter
	types.SegmentIDGetter
	types.SizeGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
}

// mockSegmentFileCopyTask is the mock task for SegmentFileCopyTask.
type mockSegmentFileCopyTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Size
	types.SourcePath
	types.SourceStorage
	types.DestinationPath
	types.DestinationStorage
	types.MD5Sum
	types.Offset
	types.SegmentID
}

func (t *mockSegmentFileCopyTask) Run() {
	panic("mockSegmentFileCopyTask should not be run.")
}

// SegmentFileCopyTask will copy a segment file.
type SegmentFileCopyTask struct {
	segmentFileCopyTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *SegmentFileCopyTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *SegmentFileCopyTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task SegmentFileCopy failed: {%w}", err))
}

// NewSegmentFileCopy will create a SegmentFileCopyTask struct and fetch inherited data from parent task.
func NewSegmentFileCopy(task navvy.Task) *SegmentFileCopyTask {
	t := &SegmentFileCopyTask{
		segmentFileCopyTaskRequirement: task.(segmentFileCopyTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewSegmentFileCopyTask will create a SegmentFileCopyTask and fetch inherited data from parent task.
func NewSegmentFileCopyTask(task navvy.Task) navvy.Task {
	return NewSegmentFileCopy(task)
}

// segmentFileCopyShimTaskRequirement is the requirement for execute SegmentFileCopyShimTask.
type segmentFileCopyShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.MD5SumGetter
	types.OffsetGetter
	types.SegmentIDGetter
	types.SizeGetter
	types.SourcePathGetter
	types.SourceStorageGetter

	// Mutable value
}

// segmentFileCopyShimTask will Storage shim task for .
type segmentFileCopyShimTask struct {
	segmentFileCopyShimTaskRequirement

	// Runtime value
	types.Storage
	types.Path
}

// Run implement navvy.Task
func (t *segmentFileCopyShimTask) Run() {}

// newSegmentFileCopyShim will create a segmentFileCopyShimTask struct and fetch inherited data from parent task.
func newSegmentFileCopyShim(task navvy.Task) *segmentFileCopyShimTask {
	t := &segmentFileCopyShimTask{
		segmentFileCopyShimTaskRequirement: task.(segmentFileCopyShimTaskRequirement),
	}
	return t
}

// segmentInitTaskRequirement is the requirement for execute SegmentInitTask.
type segmentInitTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.PathGetter
	types.ScheduleFuncGetter
	types.StorageGetter
	types.TotalSizeGetter

	// Mutable value
	types.SegmentIDSetter
}

// mockSegmentInitTask is the mock task for SegmentInitTask.
type mockSegmentInitTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Path
	types.ScheduleFunc
	types.Storage
	types.TotalSize
	types.SegmentID
}

func (t *mockSegmentInitTask) Run() {
	panic("mockSegmentInitTask should not be run.")
}

// SegmentInitTask will init a segment upload.
type SegmentInitTask struct {
	segmentInitTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *SegmentInitTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *SegmentInitTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task SegmentInit failed: {%w}", err))
}

// NewSegmentInit will create a SegmentInitTask struct and fetch inherited data from parent task.
func NewSegmentInit(task navvy.Task) *SegmentInitTask {
	t := &SegmentInitTask{
		segmentInitTaskRequirement: task.(segmentInitTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewSegmentInitTask will create a SegmentInitTask and fetch inherited data from parent task.
func NewSegmentInitTask(task navvy.Task) navvy.Task {
	return NewSegmentInit(task)
}

// segmentShimTaskRequirement is the requirement for execute SegmentShimTask.
type segmentShimTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.PartSizeGetter
	types.SegmentIDGetter
	types.SourcePathGetter
	types.SourceStorageGetter
	types.TotalSizeGetter

	// Mutable value
}

// segmentShimTask will a shim for segment operation.
type segmentShimTask struct {
	segmentShimTaskRequirement

	// Runtime value
	types.Done
	types.Offset
	types.Size
}

// Run implement navvy.Task
func (t *segmentShimTask) Run() {}

// newSegmentShim will create a segmentShimTask struct and fetch inherited data from parent task.
func newSegmentShim(task navvy.Task) *segmentShimTask {
	t := &segmentShimTask{
		segmentShimTaskRequirement: task.(segmentShimTaskRequirement),
	}
	return t
}

// segmentStreamCopyTaskRequirement is the requirement for execute SegmentStreamCopyTask.
type segmentStreamCopyTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ContentGetter
	types.DestinationPathGetter
	types.DestinationStorageGetter
	types.MD5SumGetter
	types.OffsetGetter
	types.SegmentIDGetter
	types.SizeGetter

	// Mutable value
}

// mockSegmentStreamCopyTask is the mock task for SegmentStreamCopyTask.
type mockSegmentStreamCopyTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.SegmentID
	types.Size
	types.Content
	types.DestinationPath
	types.DestinationStorage
	types.MD5Sum
	types.Offset
}

func (t *mockSegmentStreamCopyTask) Run() {
	panic("mockSegmentStreamCopyTask should not be run.")
}

// SegmentStreamCopyTask will copy a segment stream.
type SegmentStreamCopyTask struct {
	segmentStreamCopyTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
}

// Run implement navvy.Task
func (t *SegmentStreamCopyTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *SegmentStreamCopyTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task SegmentStreamCopy failed: {%w}", err))
}

// NewSegmentStreamCopy will create a SegmentStreamCopyTask struct and fetch inherited data from parent task.
func NewSegmentStreamCopy(task navvy.Task) *SegmentStreamCopyTask {
	t := &SegmentStreamCopyTask{
		segmentStreamCopyTaskRequirement: task.(segmentStreamCopyTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewSegmentStreamCopyTask will create a SegmentStreamCopyTask and fetch inherited data from parent task.
func NewSegmentStreamCopyTask(task navvy.Task) navvy.Task {
	return NewSegmentStreamCopy(task)
}

// statFileTaskRequirement is the requirement for execute StatFileTask.
type statFileTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.PathGetter
	types.StorageGetter

	// Mutable value
}

// mockStatFileTask is the mock task for StatFileTask.
type mockStatFileTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Storage
	types.Path
}

func (t *mockStatFileTask) Run() {
	panic("mockStatFileTask should not be run.")
}

// StatFileTask will stat a remote object by request headObject.
type StatFileTask struct {
	statFileTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.Object
}

// Run implement navvy.Task
func (t *StatFileTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *StatFileTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task StatFile failed: {%w}", err))
}

// NewStatFile will create a StatFileTask struct and fetch inherited data from parent task.
func NewStatFile(task navvy.Task) *StatFileTask {
	t := &StatFileTask{
		statFileTaskRequirement: task.(statFileTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewStatFileTask will create a StatFileTask and fetch inherited data from parent task.
func NewStatFileTask(task navvy.Task) navvy.Task {
	return NewStatFile(task)
}

// streamMD5SumTaskRequirement is the requirement for execute StreamMD5SumTask.
type streamMD5SumTaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter

	// Inherited value
	types.ContentGetter

	// Mutable value
}

// mockStreamMD5SumTask is the mock task for StreamMD5SumTask.
type mockStreamMD5SumTask struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
	types.Content
}

func (t *mockStreamMD5SumTask) Run() {
	panic("mockStreamMD5SumTask should not be run.")
}

// StreamMD5SumTask will get stream's md5 sum.
type StreamMD5SumTask struct {
	streamMD5SumTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Scheduler

	// Runtime value
	types.MD5Sum
}

// Run implement navvy.Task
func (t *StreamMD5SumTask) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *StreamMD5SumTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task StreamMD5Sum failed: {%w}", err))
}

// NewStreamMD5Sum will create a StreamMD5SumTask struct and fetch inherited data from parent task.
func NewStreamMD5Sum(task navvy.Task) *StreamMD5SumTask {
	t := &StreamMD5SumTask{
		streamMD5SumTaskRequirement: task.(streamMD5SumTaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// NewStreamMD5SumTask will create a StreamMD5SumTask and fetch inherited data from parent task.
func NewStreamMD5SumTask(task navvy.Task) navvy.Task {
	return NewStreamMD5Sum(task)
}
