// Code generated by go generate; DO NOT EDIT.
package task

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/pkg/types"
	"github.com/yunify/qsctl/v2/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// objectPresignTaskRequirement is the requirement for execute ObjectPresignTask.
type objectPresignTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter

	// Inherited value
	types.BucketNameGetter
	types.ExpireGetter
	types.KeyGetter
	types.StorageGetter
	// Runtime value
	types.URLSetter
}

// mockObjectPresignTask is the mock task for ObjectPresignTask.
type mockObjectPresignTask struct {
	types.Todo
	types.Pool

	// Inherited value
	types.BucketName
	types.Expire
	types.Key
	types.Storage
	// Runtime value
	types.URL
}

func (t *mockObjectPresignTask) Run() {
	panic("mockObjectPresignTask should not be run.")
}

// ObjectPresignTask will will presign a remote object and return the signed url.
type ObjectPresignTask struct {
	objectPresignTaskRequirement
}

// Run implement navvy.Task.
func (t *ObjectPresignTask) Run() {
	t.run()
	utils.SubmitNextTask(t.objectPresignTaskRequirement)
}

// NewObjectPresignTask will create a new ObjectPresignTask.
func NewObjectPresignTask(task types.Todoist) navvy.Task {
	return &ObjectPresignTask{task.(objectPresignTaskRequirement)}
}
