// Code generated by go generate; DO NOT EDIT.
package task

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/pkg/types"
	"github.com/yunify/qsctl/v2/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// objectStatTaskRequirement is the requirement for execute ObjectStatTask.
type objectStatTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter

	// Inherited value
	types.FormatGetter
	types.KeyGetter
	types.ObjectMetaGetter
	types.StorageGetter
	// Runtime value
}

// mockObjectStatTask is the mock task for ObjectStatTask.
type mockObjectStatTask struct {
	types.Todo
	types.Pool

	// Inherited value
	types.Format
	types.Key
	types.ObjectMeta
	types.Storage
	// Runtime value
}

func (t *mockObjectStatTask) Run() {
	panic("mockObjectStatTask should not be run.")
}

// ObjectStatTask will stat a remote object by request headObject.
type ObjectStatTask struct {
	objectStatTaskRequirement
}

// Run implement navvy.Task.
func (t *ObjectStatTask) Run() {
	t.run()
	utils.SubmitNextTask(t.objectStatTaskRequirement)
}

// NewObjectStatTask will create a new ObjectStatTask.
func NewObjectStatTask(task types.Todoist) navvy.Task {
	return &ObjectStatTask{task.(objectStatTaskRequirement)}
}
