// Code generated by go generate; DO NOT EDIT.
package task

import (
	"errors"
	"testing"

	"github.com/Xuanwo/navvy"
	"github.com/stretchr/testify/assert"

	"github.com/yunify/qsctl/v2/pkg/types"
)

var _ navvy.Pool
var _ types.Pool

func TestNewRemoveBucketTask(t *testing.T) {
	m := &mockRemoveBucketTask{}
	task := NewRemoveBucketTask(m)
	assert.NotNil(t, task)
}

func TestRemoveBucketTask_GeneratedRun(t *testing.T) {
	cases := []struct {
		name     string
		hasFault bool
		hasCall  bool
		gotCall  bool
	}{
		{
			"has fault",
			true,
			false,
			false,
		},
		{
			"no fault",
			false,
			true,
			false,
		},
	}

	for _, v := range cases {
		t.Run(v.name, func(t *testing.T) {
			pool := navvy.NewPool(10)

			m := &mockRemoveBucketTask{}
			m.SetPool(pool)
			task := &RemoveBucketTask{removeBucketTaskRequirement: m}

			err := errors.New("test error")
			if v.hasFault {
				task.SetFault(err)
			}
			task.GetScheduler.Sync(func(todoist types.TaskFunc) navvy.Task {
				x := utils.NewCallbackTask(func() {
					v.gotCall = true
				})
				return x
			}, task)

			task.Run()
			pool.Wait()

			assert.Equal(t, v.hasCall, v.gotCall)
		})
	}
}

func TestRemoveBucketTask_TriggerFault(t *testing.T) {
	m := &mockRemoveBucketTask{}
	task := &RemoveBucketTask{m}
	err := errors.New("test error")
	task.TriggerFault(err)
	assert.True(t, task.removeBucketTaskRequirement.ValidateFault())
}

func TestMockRemoveBucketTask_Run(t *testing.T) {
	task := &mockRemoveBucketTask{}
	assert.Panics(t, func() {
		task.Run()
	})
}
