// Code generated by go generate; DO NOT EDIT.
package task

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/pkg/types"
	"github.com/yunify/qsctl/v2/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// statTaskRequirement is the requirement for execute StatTask.
type statTaskRequirement interface {
	navvy.Task

	// Inherited value
}

// mockStatTask is the mock task for StatTask.
type mockStatTask struct {
	types.Todo
	types.Pool

	// Inherited value
}

func (t *mockStatTask) Run() {
	panic("mockStatTask should not be run.")
}

// StatTask will will stat a remote object.
type StatTask struct {
	statTaskRequirement

	// Runtime value
	types.Todo
	types.Format
	types.Key
	types.ObjectMeta
	types.Pool
	types.Storage
}

// Run implement navvy.Task
func (t *StatTask) Run() {
	utils.SubmitNextTask(t)
}

// Wait will wait until StatTask has been finished
func (t *StatTask) Wait() {
	t.GetPool().Wait()
}

// statObjectTaskRequirement is the requirement for execute StatObjectTask.
type statObjectTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter

	// Inherited value
	types.FormatGetter
	types.KeyGetter
	types.ObjectMetaGetter
	types.StorageGetter
	// Runtime value
}

// mockStatObjectTask is the mock task for StatObjectTask.
type mockStatObjectTask struct {
	types.Todo
	types.Pool

	// Inherited value
	types.Format
	types.Key
	types.ObjectMeta
	types.Storage
	// Runtime value
}

func (t *mockStatObjectTask) Run() {
	panic("mockStatObjectTask should not be run.")
}

// StatObjectTask will stat a remote object by request headObject.
type StatObjectTask struct {
	statObjectTaskRequirement
}

// Run implement navvy.Task.
func (t *StatObjectTask) Run() {
	t.run()
	utils.SubmitNextTask(t.statObjectTaskRequirement)
}

// NewStatObjectTask will create a new StatObjectTask.
func NewStatObjectTask(task types.Todoist) navvy.Task {
	return &StatObjectTask{task.(statObjectTaskRequirement)}
}
