// Code generated by go generate; DO NOT EDIT.
package task

import (
	"fmt"

	"github.com/Xuanwo/navvy"
	"github.com/google/uuid"

	"github.com/yunify/qsctl/v2/pkg/types"
	"github.com/yunify/qsctl/v2/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask
var _ = uuid.New()

// statTaskRequirement is the requirement for execute StatTask.
type statTaskRequirement interface {
	navvy.Task

	// Inherited value
}

// mockStatTask is the mock task for StatTask.
type mockStatTask struct {
	types.Todo
	types.Pool
	types.Fault
	types.ID

	// Inherited value
}

func (t *mockStatTask) Run() {
	panic("mockStatTask should not be run.")
}

// StatTask will will stat a remote object.
type StatTask struct {
	statTaskRequirement

	// Predefined runtime value
	types.Fault
	types.ID
	types.Todo

	// Runtime value
	types.Key
	types.ObjectMeta
	types.Pool
	types.Storage
}

// Run implement navvy.Task
func (t *StatTask) Run() {
	if t.ValidateFault() {
		return
	}
	utils.SubmitNextTask(t)
}

func (t *StatTask) TriggerFault(err error) {
	t.SetFault(fmt.Errorf("Task Stat failed: {%w}", err))
}

// Wait will wait until StatTask has been finished
func (t *StatTask) Wait() {
	t.GetPool().Wait()
}
