// Code generated by go generate; DO NOT EDIT.
package task

import (
	"sync"
)

type ContentLengthGetter interface {
	GetContentLength() int64
}

type ContentLengthSetter interface {
	SetContentLength(int64)
}

type ContentLength struct {
	v int64
}

func (o *ContentLength) GetContentLength() int64 {
	return o.v
}

func (o *ContentLength) SetContentLength(v int64) {
	o.v = v
}

type FilePathGetter interface {
	GetFilePath() string
}

type FilePathSetter interface {
	SetFilePath(string)
}

type FilePath struct {
	v string
}

func (o *FilePath) GetFilePath() string {
	return o.v
}

func (o *FilePath) SetFilePath(v string) {
	o.v = v
}

type MD5SumGetter interface {
	GetMD5Sum() []byte
}

type MD5SumSetter interface {
	SetMD5Sum([]byte)
}

type MD5Sum struct {
	v []byte
}

func (o *MD5Sum) GetMD5Sum() []byte {
	return o.v
}

func (o *MD5Sum) SetMD5Sum(v []byte) {
	o.v = v
}

type ObjectKeyGetter interface {
	GetObjectKey() string
}

type ObjectKeySetter interface {
	SetObjectKey(string)
}

type ObjectKey struct {
	v string
}

func (o *ObjectKey) GetObjectKey() string {
	return o.v
}

func (o *ObjectKey) SetObjectKey(v string) {
	o.v = v
}

type OffsetGetter interface {
	GetOffset() int64
}

type OffsetSetter interface {
	SetOffset(int64)
}

type Offset struct {
	v int64
}

func (o *Offset) GetOffset() int64 {
	return o.v
}

func (o *Offset) SetOffset(v int64) {
	o.v = v
}

type PartNumberGetter interface {
	GetPartNumber() int
}

type PartNumberSetter interface {
	SetPartNumber(int)
}

type PartNumber struct {
	v int
}

func (o *PartNumber) GetPartNumber() int {
	return o.v
}

func (o *PartNumber) SetPartNumber(v int) {
	o.v = v
}

type TotalPartsGetter interface {
	GetTotalParts() int
}

type TotalPartsSetter interface {
	SetTotalParts(int)
}

type TotalParts struct {
	v int
}

func (o *TotalParts) GetTotalParts() int {
	return o.v
}

func (o *TotalParts) SetTotalParts(v int) {
	o.v = v
}

type UploadIDGetter interface {
	GetUploadID() string
}

type UploadIDSetter interface {
	SetUploadID(string)
}

type UploadID struct {
	v string
}

func (o *UploadID) GetUploadID() string {
	return o.v
}

func (o *UploadID) SetUploadID(v string) {
	o.v = v
}

type WaitGroupGetter interface {
	GetWaitGroup() *sync.WaitGroup
}

type WaitGroupSetter interface {
	SetWaitGroup(*sync.WaitGroup)
}

type WaitGroup struct {
	v *sync.WaitGroup
}

func (o *WaitGroup) GetWaitGroup() *sync.WaitGroup {
	return o.v
}

func (o *WaitGroup) SetWaitGroup(v *sync.WaitGroup) {
	o.v = v
}
