// Code generated by go generate; DO NOT EDIT.
package common

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/task/types"
	"github.com/yunify/qsctl/v2/task/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// FileMD5SumTaskRequirement is the requirement for execute FileMD5SumTask.
type FileMD5SumTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter
	types.MD5SumSetter
	types.PathGetter
	types.OffsetGetter
	types.SizeGetter
}

// FileMD5SumTask will get file's md5 sum.
type FileMD5SumTask struct {
	FileMD5SumTaskRequirement
}

// mockFileMD5SumTask is the mock task for FileMD5SumTask.
type mockFileMD5SumTask struct {
	types.Todo
	types.Pool
	types.MD5Sum
	types.Path
	types.Offset
	types.Size
}

func (t *mockFileMD5SumTask) Run() {
	panic("mockFileMD5SumTask should not be run.")
}

// NewFileMD5SumTask will create a new FileMD5SumTask.
func NewFileMD5SumTask(task types.Todoist) navvy.Task {
	return &FileMD5SumTask{task.(FileMD5SumTaskRequirement)}
}

// StreamMD5SumTaskRequirement is the requirement for execute StreamMD5SumTask.
type StreamMD5SumTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter
	types.MD5SumSetter
	types.ContentGetter
}

// StreamMD5SumTask will get stream's md5 sum.
type StreamMD5SumTask struct {
	StreamMD5SumTaskRequirement
}

// mockStreamMD5SumTask is the mock task for StreamMD5SumTask.
type mockStreamMD5SumTask struct {
	types.Todo
	types.Pool
	types.MD5Sum
	types.Content
}

func (t *mockStreamMD5SumTask) Run() {
	panic("mockStreamMD5SumTask should not be run.")
}

// NewStreamMD5SumTask will create a new StreamMD5SumTask.
func NewStreamMD5SumTask(task types.Todoist) navvy.Task {
	return &StreamMD5SumTask{task.(StreamMD5SumTaskRequirement)}
}
