// Code generated by go generate; DO NOT EDIT.
package common

import (
	"errors"
	"testing"

	"github.com/Xuanwo/navvy"
	"github.com/stretchr/testify/assert"

	"github.com/yunify/qsctl/v2/pkg/types"
)

var _ navvy.Pool
var _ types.Pool

func TestNewFileMD5SumTask(t *testing.T) {
	m := &mockFileMD5SumTask{}
	task := NewFileMD5SumTask(m)
	assert.NotNil(t, task)
}

func TestFileMD5SumTask_GeneratedRun(t *testing.T) {
	cases := []struct {
		name     string
		hasFault bool
		hasCall  bool
		gotCall  bool
	}{
		{
			"has fault",
			true,
			false,
			false,
		},
		{
			"no fault",
			false,
			true,
			false,
		},
	}

	for _, v := range cases {
		t.Run(v.name, func(t *testing.T) {
			pool := navvy.NewPool(10)

			m := &mockFileMD5SumTask{}
			m.SetPool(pool)
			task := &FileMD5SumTask{fileMD5SumTaskRequirement: m}

			err := errors.New("test error")
			if v.hasFault {
				task.SetFault(err)
			}
			task.GetScheduler.Sync(func(todoist types.TaskFunc) navvy.Task {
				x := utils.NewCallbackTask(func() {
					v.gotCall = true
				})
				return x
			}, task)

			task.Run()
			pool.Wait()

			assert.Equal(t, v.hasCall, v.gotCall)
		})
	}
}

func TestFileMD5SumTask_TriggerFault(t *testing.T) {
	m := &mockFileMD5SumTask{}
	task := &FileMD5SumTask{m}
	err := errors.New("test error")
	task.TriggerFault(err)
	assert.True(t, task.fileMD5SumTaskRequirement.ValidateFault())
}

func TestMockFileMD5SumTask_Run(t *testing.T) {
	task := &mockFileMD5SumTask{}
	assert.Panics(t, func() {
		task.Run()
	})
}

func TestNewStreamMD5SumTask(t *testing.T) {
	m := &mockStreamMD5SumTask{}
	task := NewStreamMD5SumTask(m)
	assert.NotNil(t, task)
}

func TestStreamMD5SumTask_GeneratedRun(t *testing.T) {
	cases := []struct {
		name     string
		hasFault bool
		hasCall  bool
		gotCall  bool
	}{
		{
			"has fault",
			true,
			false,
			false,
		},
		{
			"no fault",
			false,
			true,
			false,
		},
	}

	for _, v := range cases {
		t.Run(v.name, func(t *testing.T) {
			pool := navvy.NewPool(10)

			m := &mockStreamMD5SumTask{}
			m.SetPool(pool)
			task := &StreamMD5SumTask{streamMD5SumTaskRequirement: m}

			err := errors.New("test error")
			if v.hasFault {
				task.SetFault(err)
			}
			task.GetScheduler.Sync(func(todoist types.TaskFunc) navvy.Task {
				x := utils.NewCallbackTask(func() {
					v.gotCall = true
				})
				return x
			}, task)

			task.Run()
			pool.Wait()

			assert.Equal(t, v.hasCall, v.gotCall)
		})
	}
}

func TestStreamMD5SumTask_TriggerFault(t *testing.T) {
	m := &mockStreamMD5SumTask{}
	task := &StreamMD5SumTask{m}
	err := errors.New("test error")
	task.TriggerFault(err)
	assert.True(t, task.streamMD5SumTaskRequirement.ValidateFault())
}

func TestMockStreamMD5SumTask_Run(t *testing.T) {
	task := &mockStreamMD5SumTask{}
	assert.Panics(t, func() {
		task.Run()
	})
}
