// Code generated by go generate; DO NOT EDIT.
package common

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/pkg/types"
	"github.com/yunify/qsctl/v2/task/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// fileMD5SumTaskRequirement is the requirement for execute FileMD5SumTask.
type fileMD5SumTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter

	// Inherited value
	types.OffsetGetter
	types.PathGetter
	types.SizeGetter
	// Runtime value
	types.MD5SumSetter
}

// mockFileMD5SumTask is the mock task for FileMD5SumTask.
type mockFileMD5SumTask struct {
	types.Todo
	types.Pool

	// Inherited value
	types.Offset
	types.Path
	types.Size
	// Runtime value
	types.MD5Sum
}

func (t *mockFileMD5SumTask) Run() {
	panic("mockFileMD5SumTask should not be run.")
}

// FileMD5SumTask will get file's md5 sum.
type FileMD5SumTask struct {
	fileMD5SumTaskRequirement
}

// Run implement navvy.Task.
func (t *FileMD5SumTask) Run() {
	t.run()
	utils.SubmitNextTask(t.fileMD5SumTaskRequirement)
}

// NewFileMD5SumTask will create a new FileMD5SumTask.
func NewFileMD5SumTask(task types.Todoist) navvy.Task {
	return &FileMD5SumTask{task.(fileMD5SumTaskRequirement)}
}

// streamMD5SumTaskRequirement is the requirement for execute StreamMD5SumTask.
type streamMD5SumTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter

	// Inherited value
	types.ContentGetter
	// Runtime value
	types.MD5SumSetter
}

// mockStreamMD5SumTask is the mock task for StreamMD5SumTask.
type mockStreamMD5SumTask struct {
	types.Todo
	types.Pool

	// Inherited value
	types.Content
	// Runtime value
	types.MD5Sum
}

func (t *mockStreamMD5SumTask) Run() {
	panic("mockStreamMD5SumTask should not be run.")
}

// StreamMD5SumTask will get stream's md5 sum.
type StreamMD5SumTask struct {
	streamMD5SumTaskRequirement
}

// Run implement navvy.Task.
func (t *StreamMD5SumTask) Run() {
	t.run()
	utils.SubmitNextTask(t.streamMD5SumTaskRequirement)
}

// NewStreamMD5SumTask will create a new StreamMD5SumTask.
func NewStreamMD5SumTask(task types.Todoist) navvy.Task {
	return &StreamMD5SumTask{task.(streamMD5SumTaskRequirement)}
}
