// Code generated by go generate; DO NOT EDIT.
package common

import (
	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/task/types"
	"github.com/yunify/qsctl/v2/task/utils"
)

var _ navvy.Pool
var _ types.Pool
var _ = utils.SubmitNextTask

// MultipartCompleteTaskRequirement is the requirement for execute MultipartCompleteTask.
type MultipartCompleteTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter
	types.KeyGetter
	types.UploadIDGetter
	types.CurrentPartNumberGetter
	types.StorageGetter
}

// MultipartCompleteTask will upload a multipart via stream.
type MultipartCompleteTask struct {
	MultipartCompleteTaskRequirement
}

// mockMultipartCompleteTask is the mock task for MultipartCompleteTask.
type mockMultipartCompleteTask struct {
	types.Todo
	types.Pool
	types.Key
	types.UploadID
	types.CurrentPartNumber
	types.Storage
}

func (t *mockMultipartCompleteTask) Run() {
	panic("mockMultipartCompleteTask should not be run.")
}

// NewMultipartCompleteTask will create a new MultipartCompleteTask.
func NewMultipartCompleteTask(task types.Todoist) navvy.Task {
	return &MultipartCompleteTask{task.(MultipartCompleteTaskRequirement)}
}

// MultipartFileUploadTaskRequirement is the requirement for execute MultipartFileUploadTask.
type MultipartFileUploadTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter
	types.MD5SumGetter
	types.PathGetter
	types.KeyGetter
	types.OffsetGetter
	types.UploadIDGetter
	types.PartNumberGetter
	types.SizeGetter
	types.WaitGroupGetter
	types.StorageGetter
}

// MultipartFileUploadTask will upload a multipart via file.
type MultipartFileUploadTask struct {
	MultipartFileUploadTaskRequirement
}

// mockMultipartFileUploadTask is the mock task for MultipartFileUploadTask.
type mockMultipartFileUploadTask struct {
	types.Todo
	types.Pool
	types.MD5Sum
	types.Path
	types.Key
	types.Offset
	types.UploadID
	types.PartNumber
	types.Size
	types.WaitGroup
	types.Storage
}

func (t *mockMultipartFileUploadTask) Run() {
	panic("mockMultipartFileUploadTask should not be run.")
}

// NewMultipartFileUploadTask will create a new MultipartFileUploadTask.
func NewMultipartFileUploadTask(task types.Todoist) navvy.Task {
	return &MultipartFileUploadTask{task.(MultipartFileUploadTaskRequirement)}
}

// MultipartInitTaskRequirement is the requirement for execute MultipartInitTask.
type MultipartInitTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter
	types.KeyGetter
	types.PathGetter
	types.UploadIDSetter
	types.WaitGroupGetter
	types.StorageGetter
	types.TaskConstructorGetter
	types.CurrentPartNumberGetter
	types.CurrentOffsetGetter
	types.PartSizeGetter
	types.SizeGetter
}

// MultipartInitTask will init a multipart upload.
type MultipartInitTask struct {
	MultipartInitTaskRequirement
}

// mockMultipartInitTask is the mock task for MultipartInitTask.
type mockMultipartInitTask struct {
	types.Todo
	types.Pool
	types.Key
	types.Path
	types.UploadID
	types.WaitGroup
	types.Storage
	types.TaskConstructor
	types.CurrentPartNumber
	types.CurrentOffset
	types.PartSize
	types.Size
}

func (t *mockMultipartInitTask) Run() {
	panic("mockMultipartInitTask should not be run.")
}

// NewMultipartInitTask will create a new MultipartInitTask.
func NewMultipartInitTask(task types.Todoist) navvy.Task {
	return &MultipartInitTask{task.(MultipartInitTaskRequirement)}
}

// MultipartStreamUploadTaskRequirement is the requirement for execute MultipartStreamUploadTask.
type MultipartStreamUploadTaskRequirement interface {
	navvy.Task
	types.Todoist
	types.PoolGetter
	types.MD5SumGetter
	types.PathGetter
	types.KeyGetter
	types.UploadIDGetter
	types.PartNumberGetter
	types.SizeGetter
	types.WaitGroupGetter
	types.StorageGetter
	types.ContentGetter
}

// MultipartStreamUploadTask will upload a multipart via stream.
type MultipartStreamUploadTask struct {
	MultipartStreamUploadTaskRequirement
}

// mockMultipartStreamUploadTask is the mock task for MultipartStreamUploadTask.
type mockMultipartStreamUploadTask struct {
	types.Todo
	types.Pool
	types.MD5Sum
	types.Path
	types.Key
	types.UploadID
	types.PartNumber
	types.Size
	types.WaitGroup
	types.Storage
	types.Content
}

func (t *mockMultipartStreamUploadTask) Run() {
	panic("mockMultipartStreamUploadTask should not be run.")
}

// NewMultipartStreamUploadTask will create a new MultipartStreamUploadTask.
func NewMultipartStreamUploadTask(task types.Todoist) navvy.Task {
	return &MultipartStreamUploadTask{task.(MultipartStreamUploadTaskRequirement)}
}
