// The following directive is necessary to make the package coherent:
// This program generates types, It can be invoked by running
// go generate
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"sort"
	"strings"
	"text/template"
)

type task struct {
	Name           string   `json:"-"`
	Description    string   `json:"description"`
	InheritedValue []string `json:"inherited_value,omitempty"`
	MutableValue   []string `json:"mutable_value,omitempty"`
	RuntimeValue   []string `json:"runtime_value,omitempty"`
}

var funcs = template.FuncMap{
	"lowerFirst": func(s string) string {
		if len(s) == 0 {
			return ""
		}
		if s[0] < 'A' || s[0] > 'Z' {
			return s
		}
		return string(s[0]+'a'-'A') + s[1:]
	},
	"endwith": func(x, y string) bool {
		return strings.HasSuffix(x, y)
	},
	"merge": func(x, y []string) []string {
		a := make(map[string]struct{})
		for _, v := range x {
			a[v] = struct{}{}
		}
		for _, v := range y {
			a[v] = struct{}{}
		}
		o := make([]string, 0)
		for x := range a {
			o = append(o, x)
		}
		return o
	},
}

func hasBetweenSubString(s []string, x string) bool {
	str := strings.Join(s, " ")
	return strings.Contains(str, "Source"+x) && strings.Contains(str, "Destination"+x)
}

func main() {
	data, err := ioutil.ReadFile("tasks.json")
	if err != nil {
		log.Fatal(err)
	}

	tasks := make(map[string]*task)
	err = json.Unmarshal(data, &tasks)
	if err != nil {
		log.Fatal(err)
	}

	// Do sort to all tasks via name.
	taskNames := make([]string, 0)
	for k := range tasks {
		sort.Strings(tasks[k].InheritedValue)
		sort.Strings(tasks[k].RuntimeValue)

		taskNames = append(taskNames, k)
	}
	sort.Strings(taskNames)

	// Format input tasks.json
	data, err = json.MarshalIndent(tasks, "", "  ")
	if err != nil {
		log.Fatal(err)
	}
	err = ioutil.WriteFile("tasks.json", data, 0664)
	if err != nil {
		log.Fatal(err)
	}

	// Add shims for storage.
	shimTasks := make(map[string]*task)
	for k, v := range tasks {
		if strings.HasSuffix(k, "Shim") {
			continue
		}

		t := *v
		t.Name += k + "Shim"
		t.Description = fmt.Sprintf("Storage shim task for %s", v.Name)
		t.InheritedValue = append(t.InheritedValue, t.RuntimeValue...)
		t.MutableValue = append(t.MutableValue, t.RuntimeValue...)

		t.RuntimeValue = nil
		for _, s := range []string{"Storage", "Path", "Type"} {
			if hasBetweenSubString(t.InheritedValue, s) {
				t.RuntimeValue = append(t.RuntimeValue, s)
			}
		}
		if len(t.RuntimeValue) == 0 {
			continue
		}
		shimTasks[t.Name] = &t
	}
	for k, v := range shimTasks {
		v := v
		tasks[k] = v
		taskNames = append(taskNames, k)
	}
	sort.Strings(taskNames)

	taskFile, err := os.Create("generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer taskFile.Close()

	testFile, err := os.Create("generated_test.go")
	if err != nil {
		log.Fatal(err)
	}
	defer testFile.Close()

	// Write page temple firstly.
	err = pageTmpl.Execute(taskFile, nil)
	if err != nil {
		log.Fatal(err)
	}

	// Write page temple firstly.
	err = testPageTmpl.Execute(testFile, nil)
	if err != nil {
		log.Fatal(err)
	}

	for _, taskName := range taskNames {
		v := tasks[taskName]
		v.Name = taskName

		// Write task.
		err = requirementTmpl.Execute(taskFile, v)
		if err != nil {
			log.Fatal(err)
		}
		if strings.HasSuffix(taskName, "Shim") {
			err = shimTaskTmpl.Execute(taskFile, v)
			if err != nil {
				log.Fatal(err)
			}
		} else {
			err = mockTmpl.Execute(taskFile, v)
			if err != nil {
				log.Fatal(err)
			}
			err = taskTmpl.Execute(taskFile, v)
			if err != nil {
				log.Fatal(err)
			}

			// Write test.
			err = taskTestTmpl.Execute(testFile, v)
			if err != nil {
				log.Fatal(err)
			}
		}
	}
}

var pageTmpl = template.Must(template.New("page").Parse(`// Code generated by go generate; DO NOT EDIT.
package task

import (
	"fmt"

	"github.com/Xuanwo/navvy"
	"github.com/google/uuid"

	"github.com/yunify/qsctl/v2/pkg/types"
	"github.com/yunify/qsctl/v2/pkg/schedule"
)

var _ navvy.Pool
var _ types.Pool
var _ = uuid.New()
`))

var testPageTmpl = template.Must(template.New("testPage").Parse(`// Code generated by go generate; DO NOT EDIT.
package task

import (
	"errors"
	"testing"

	"github.com/Xuanwo/navvy"
	"github.com/stretchr/testify/assert"

	"github.com/yunify/qsctl/v2/pkg/types"
)

var _ navvy.Pool
var _ types.Pool
`))

var requirementTmpl = template.Must(template.New("requirement").Funcs(funcs).Parse(`
// {{ .Name | lowerFirst }}TaskRequirement is the requirement for execute {{ .Name }}Task.
type {{ .Name | lowerFirst }}TaskRequirement interface {
	navvy.Task

	// Predefined inherited value
	types.PoolGetter
	types.FaultGetter

	// Inherited value
{{- range $k, $v := .InheritedValue }}
	types.{{$v}}Getter
{{- end }}

	// Mutable value
{{- range $k, $v := .MutableValue }}
	types.{{$v}}Setter
{{- end }}
}
`))

var mockTmpl = template.Must(template.New("mock").Funcs(funcs).Parse(`
// mock{{ .Name }}Task is the mock task for {{ .Name }}Task.
type mock{{ .Name }}Task struct {
	types.Pool
	types.Fault
	types.ID

	// Inherited and mutable values.
{{- range $k, $v := merge .InheritedValue .MutableValue}}
	types.{{$v}}
{{- end }}
}

func (t *mock{{ .Name }}Task) Run() {
	panic("mock{{ .Name }}Task should not be run.")
}
`))

var taskTmpl = template.Must(template.New("task").Funcs(funcs).Parse(`
// {{ .Name }}Task will {{ .Description }}.
type {{ .Name }}Task struct {
	{{ .Name | lowerFirst }}TaskRequirement

	// Predefined runtime value
	types.ID
	types.Scheduler

	// Runtime value
{{- range $k, $v := .RuntimeValue }}
	types.{{$v}}
{{- end }}
}

// Run implement navvy.Task
func (t *{{ .Name }}Task) Run() {
	t.run()
	t.GetScheduler().Wait()
}

func (t *{{ .Name }}Task) TriggerFault(err error) {
	t.GetFault().Append(fmt.Errorf("Task ListFile failed: {%w}", err))
}

// New{{ .Name }} will create a {{ .Name }}Task struct and fetch inherited data from parent task.
func New{{ .Name }}(task navvy.Task) *{{ .Name }}Task {
	t := &{{ .Name }}Task{
		{{ .Name | lowerFirst }}TaskRequirement: task.({{ .Name | lowerFirst }}TaskRequirement),
	}
	t.SetID(uuid.New().String())
	t.SetScheduler(schedule.NewScheduler(t.GetPool()))

	t.new()
	return t
}

// New{{ .Name }}Task will create a {{ .Name }}Task and fetch inherited data from parent task.
func New{{ .Name }}Task(task navvy.Task) navvy.Task {
	return New{{ .Name }}(task)
}
`))

var shimTaskTmpl = template.Must(template.New("shimTask").Funcs(funcs).Parse(`
{{ $name := .Name | lowerFirst }}
// {{ $name }}Task will {{ .Description }}.
type {{ $name }}Task struct {
	{{ $name }}TaskRequirement

	// Runtime value
{{- range $k, $v := .RuntimeValue }}
	types.{{$v}}
{{- end }}
}

// Run implement navvy.Task
func (t *{{ $name }}Task) Run() {}

// new{{ .Name }} will create a {{ $name }}Task struct and fetch inherited data from parent task.
func new{{ .Name }}(task navvy.Task) *{{ $name }}Task {
	t := &{{ $name }}Task{
		{{ $name }}TaskRequirement: task.({{ $name }}TaskRequirement),
	}
	return t
}
`))

var taskTestTmpl = template.Must(template.New("taskTest").Funcs(funcs).Parse(`
func Test{{ .Name }}Task_TriggerFault(t *testing.T) {
	m := &mock{{ .Name }}Task{}
	task := &{{ .Name }}Task{ {{ .Name | lowerFirst }}TaskRequirement: m}
	err := errors.New("test error")
	task.TriggerFault(err)
	assert.True(t, task.GetFault().HasError())
}

func TestMock{{ .Name }}Task_Run(t *testing.T) {
	task := &mock{{ .Name }}Task{}
	assert.Panics(t, func() {
		task.Run()
	})
}
`))
