// Code generated by go generate; DO NOT EDIT.
package types

import (
	"sync"

	"github.com/Xuanwo/navvy"

	"github.com/yunify/qsctl/v2/storage"
)

type BytesBufferPoolGetter interface {
	GetBytesBufferPool() *sync.Pool
}

type BytesBufferPoolSetter interface {
	SetBytesBufferPool(*sync.Pool)
}

type BytesBufferPool struct {
	valid bool
	v *sync.Pool
}

func (o *BytesBufferPool) GetBytesBufferPool() *sync.Pool {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *BytesBufferPool) SetBytesBufferPool(v *sync.Pool) {
	o.v = v
	o.valid = true
}

type ContentGetter interface {
	GetContent() *bytes.Buffer
}

type ContentSetter interface {
	SetContent(*bytes.Buffer)
}

type Content struct {
	valid bool
	v *bytes.Buffer
}

func (o *Content) GetContent() *bytes.Buffer {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *Content) SetContent(v *bytes.Buffer) {
	o.v = v
	o.valid = true
}

type EnableBenchmarkGetter interface {
	GetEnableBenchmark() bool
}

type EnableBenchmarkSetter interface {
	SetEnableBenchmark(bool)
}

type EnableBenchmark struct {
	valid bool
	v bool
}

func (o *EnableBenchmark) GetEnableBenchmark() bool {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *EnableBenchmark) SetEnableBenchmark(v bool) {
	o.v = v
	o.valid = true
}

type ExpectSizeGetter interface {
	GetExpectSize() int64
}

type ExpectSizeSetter interface {
	SetExpectSize(int64)
}

type ExpectSize struct {
	valid bool
	v int64
}

func (o *ExpectSize) GetExpectSize() int64 {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *ExpectSize) SetExpectSize(v int64) {
	o.v = v
	o.valid = true
}

type FilePathGetter interface {
	GetFilePath() string
}

type FilePathSetter interface {
	SetFilePath(string)
}

type FilePath struct {
	valid bool
	v string
}

func (o *FilePath) GetFilePath() string {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *FilePath) SetFilePath(v string) {
	o.v = v
	o.valid = true
}

type FlowGetter interface {
	GetFlow() string
}

type FlowSetter interface {
	SetFlow(string)
}

type Flow struct {
	valid bool
	v string
}

func (o *Flow) GetFlow() string {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *Flow) SetFlow(v string) {
	o.v = v
	o.valid = true
}

type MD5SumGetter interface {
	GetMD5Sum() []byte
}

type MD5SumSetter interface {
	SetMD5Sum([]byte)
}

type MD5Sum struct {
	valid bool
	v []byte
}

func (o *MD5Sum) GetMD5Sum() []byte {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *MD5Sum) SetMD5Sum(v []byte) {
	o.v = v
	o.valid = true
}

type ObjectKeyGetter interface {
	GetObjectKey() string
}

type ObjectKeySetter interface {
	SetObjectKey(string)
}

type ObjectKey struct {
	valid bool
	v string
}

func (o *ObjectKey) GetObjectKey() string {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *ObjectKey) SetObjectKey(v string) {
	o.v = v
	o.valid = true
}

type OffsetGetter interface {
	GetOffset() int64
}

type OffsetSetter interface {
	SetOffset(int64)
}

type Offset struct {
	valid bool
	v int64
}

func (o *Offset) GetOffset() int64 {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *Offset) SetOffset(v int64) {
	o.v = v
	o.valid = true
}

type PartNumberGetter interface {
	GetPartNumber() int
}

type PartNumberSetter interface {
	SetPartNumber(int)
}

type PartNumber struct {
	valid bool
	v int
}

func (o *PartNumber) GetPartNumber() int {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *PartNumber) SetPartNumber(v int) {
	o.v = v
	o.valid = true
}

type PoolGetter interface {
	GetPool() *navvy.Pool
}

type PoolSetter interface {
	SetPool(*navvy.Pool)
}

type Pool struct {
	valid bool
	v *navvy.Pool
}

func (o *Pool) GetPool() *navvy.Pool {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *Pool) SetPool(v *navvy.Pool) {
	o.v = v
	o.valid = true
}

type SizeGetter interface {
	GetSize() int64
}

type SizeSetter interface {
	SetSize(int64)
}

type Size struct {
	valid bool
	v int64
}

func (o *Size) GetSize() int64 {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *Size) SetSize(v int64) {
	o.v = v
	o.valid = true
}

type StorageGetter interface {
	GetStorage() storage.ObjectStorage
}

type StorageSetter interface {
	SetStorage(storage.ObjectStorage)
}

type Storage struct {
	valid bool
	v storage.ObjectStorage
}

func (o *Storage) GetStorage() storage.ObjectStorage {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *Storage) SetStorage(v storage.ObjectStorage) {
	o.v = v
	o.valid = true
}

type TotalPartsGetter interface {
	GetTotalParts() int
}

type TotalPartsSetter interface {
	SetTotalParts(int)
}

type TotalParts struct {
	valid bool
	v int
}

func (o *TotalParts) GetTotalParts() int {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *TotalParts) SetTotalParts(v int) {
	o.v = v
	o.valid = true
}

type UploadIDGetter interface {
	GetUploadID() string
}

type UploadIDSetter interface {
	SetUploadID(string)
}

type UploadID struct {
	valid bool
	v string
}

func (o *UploadID) GetUploadID() string {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *UploadID) SetUploadID(v string) {
	o.v = v
	o.valid = true
}

type WaitGroupGetter interface {
	GetWaitGroup() *sync.WaitGroup
}

type WaitGroupSetter interface {
	SetWaitGroup(*sync.WaitGroup)
}

type WaitGroup struct {
	valid bool
	v *sync.WaitGroup
}

func (o *WaitGroup) GetWaitGroup() *sync.WaitGroup {
	if !o.valid {
		panic("value is not valid")
	}
	return o.v
}

func (o *WaitGroup) SetWaitGroup(v *sync.WaitGroup) {
	o.v = v
	o.valid = true
}

