// Code generated by go generate; DO NOT EDIT.
package types

import (
	"github.com/Xuanwo/navvy"
)

// PathRequirement is the requirement for PathTask.
type PathRequirement interface {
	navvy.Task

	// Value
	PathGetter
	PathSetter
	PathValidator
	StorageGetter
	StorageSetter
	StorageValidator
}

type pathScheduleFunc func(navvy.Task) PathRequirement

// SegmentRequirement is the requirement for SegmentTask.
type SegmentRequirement interface {
	navvy.Task

	// Value
	DoneGetter
	DoneSetter
	DoneValidator
	SizeGetter
	SizeSetter
	SizeValidator
}

type segmentScheduleFunc func(navvy.Task) SegmentRequirement
