name: "Unit Test"

on:
  push:
  pull_request:

jobs:
  unit_test:
    name: Unit Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        go: [ "1.16", "1.17" ]
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest

      - name: Build
        run: make build

      - name: Test
        run: make test
